---
# Example that prints the loopback address and gateway for each host
- command: /usr/bin/uptime
  register: result

- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} and uptime is {{ result }}" 
